/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ChannelEngine.Api.Client.Client.SwaggerDateConverter;

namespace ChannelEngine.Api.Client.Model
{
    /// <summary>
    /// MerchantStockPriceUpdateRequest
    /// </summary>
    [DataContract]
    public partial class MerchantStockPriceUpdateRequest :  IEquatable<MerchantStockPriceUpdateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantStockPriceUpdateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MerchantStockPriceUpdateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantStockPriceUpdateRequest" /> class.
        /// </summary>
        /// <param name="MerchantProductNo">MerchantProductNo (required).</param>
        /// <param name="Stock">Stock.</param>
        /// <param name="Price">Price.</param>
        public MerchantStockPriceUpdateRequest(string MerchantProductNo = default(string), int? Stock = default(int?), double? Price = default(double?))
        {
            // to ensure "MerchantProductNo" is required (not null)
            if (MerchantProductNo == null)
            {
                throw new InvalidDataException("MerchantProductNo is a required property for MerchantStockPriceUpdateRequest and cannot be null");
            }
            else
            {
                this.MerchantProductNo = MerchantProductNo;
            }
            this.Stock = Stock;
            this.Price = Price;
        }
        
        /// <summary>
        /// Gets or Sets MerchantProductNo
        /// </summary>
        [DataMember(Name="MerchantProductNo", EmitDefaultValue=false)]
        public string MerchantProductNo { get; set; }

        /// <summary>
        /// Gets or Sets Stock
        /// </summary>
        [DataMember(Name="Stock", EmitDefaultValue=false)]
        public int? Stock { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="Price", EmitDefaultValue=false)]
        public double? Price { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MerchantStockPriceUpdateRequest {\n");
            sb.Append("  MerchantProductNo: ").Append(MerchantProductNo).Append("\n");
            sb.Append("  Stock: ").Append(Stock).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MerchantStockPriceUpdateRequest);
        }

        /// <summary>
        /// Returns true if MerchantStockPriceUpdateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of MerchantStockPriceUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MerchantStockPriceUpdateRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.MerchantProductNo == other.MerchantProductNo ||
                    this.MerchantProductNo != null &&
                    this.MerchantProductNo.Equals(other.MerchantProductNo)
                ) && 
                (
                    this.Stock == other.Stock ||
                    this.Stock != null &&
                    this.Stock.Equals(other.Stock)
                ) && 
                (
                    this.Price == other.Price ||
                    this.Price != null &&
                    this.Price.Equals(other.Price)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.MerchantProductNo != null)
                    hash = hash * 59 + this.MerchantProductNo.GetHashCode();
                if (this.Stock != null)
                    hash = hash * 59 + this.Stock.GetHashCode();
                if (this.Price != null)
                    hash = hash * 59 + this.Price.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
