/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing EntitiesAddressModels
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntitiesAddressModelsTests
    {
        // TODO uncomment below to declare an instance variable for EntitiesAddressModels
        //private EntitiesAddressModels instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntitiesAddressModels
            //instance = new EntitiesAddressModels();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntitiesAddressModels
        /// </summary>
        [Test]
        public void EntitiesAddressModelsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntitiesAddressModels
            //Assert.IsInstanceOfType<EntitiesAddressModels> (instance, "variable 'instance' is a EntitiesAddressModels");
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'StreetName'
        /// </summary>
        [Test]
        public void StreetNameTest()
        {
            // TODO unit test for the property 'StreetName'
        }
        /// <summary>
        /// Test the property 'HouseNr'
        /// </summary>
        [Test]
        public void HouseNrTest()
        {
            // TODO unit test for the property 'HouseNr'
        }
        /// <summary>
        /// Test the property 'HouseNrAddition'
        /// </summary>
        [Test]
        public void HouseNrAdditionTest()
        {
            // TODO unit test for the property 'HouseNrAddition'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Test]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'CountryIso'
        /// </summary>
        [Test]
        public void CountryIsoTest()
        {
            // TODO unit test for the property 'CountryIso'
        }
        /// <summary>
        /// Test the property 'Original'
        /// </summary>
        [Test]
        public void OriginalTest()
        {
            // TODO unit test for the property 'Original'
        }

    }

}
