/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing MerchantOrderLineResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MerchantOrderLineResponseTests
    {
        // TODO uncomment below to declare an instance variable for MerchantOrderLineResponse
        //private MerchantOrderLineResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantOrderLineResponse
            //instance = new MerchantOrderLineResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantOrderLineResponse
        /// </summary>
        [Test]
        public void MerchantOrderLineResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchantOrderLineResponse
            //Assert.IsInstanceOfType<MerchantOrderLineResponse> (instance, "variable 'instance' is a MerchantOrderLineResponse");
        }

        /// <summary>
        /// Test the property 'MerchantProductNo'
        /// </summary>
        [Test]
        public void MerchantProductNoTest()
        {
            // TODO unit test for the property 'MerchantProductNo'
        }
        /// <summary>
        /// Test the property 'ChannelProductNo'
        /// </summary>
        [Test]
        public void ChannelProductNoTest()
        {
            // TODO unit test for the property 'ChannelProductNo'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'UnitPriceInclVat'
        /// </summary>
        [Test]
        public void UnitPriceInclVatTest()
        {
            // TODO unit test for the property 'UnitPriceInclVat'
        }
        /// <summary>
        /// Test the property 'FeeFixed'
        /// </summary>
        [Test]
        public void FeeFixedTest()
        {
            // TODO unit test for the property 'FeeFixed'
        }
        /// <summary>
        /// Test the property 'FeeRate'
        /// </summary>
        [Test]
        public void FeeRateTest()
        {
            // TODO unit test for the property 'FeeRate'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

    }

}
