/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing MerchantReturnLineRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MerchantReturnLineRequestTests
    {
        // TODO uncomment below to declare an instance variable for MerchantReturnLineRequest
        //private MerchantReturnLineRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantReturnLineRequest
            //instance = new MerchantReturnLineRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantReturnLineRequest
        /// </summary>
        [Test]
        public void MerchantReturnLineRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchantReturnLineRequest
            //Assert.IsInstanceOfType<MerchantReturnLineRequest> (instance, "variable 'instance' is a MerchantReturnLineRequest");
        }

        /// <summary>
        /// Test the property 'MerchantProductNo'
        /// </summary>
        [Test]
        public void MerchantProductNoTest()
        {
            // TODO unit test for the property 'MerchantProductNo'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
