/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing MerchantShipmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MerchantShipmentRequestTests
    {
        // TODO uncomment below to declare an instance variable for MerchantShipmentRequest
        //private MerchantShipmentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantShipmentRequest
            //instance = new MerchantShipmentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantShipmentRequest
        /// </summary>
        [Test]
        public void MerchantShipmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchantShipmentRequest
            //Assert.IsInstanceOfType<MerchantShipmentRequest> (instance, "variable 'instance' is a MerchantShipmentRequest");
        }

        /// <summary>
        /// Test the property 'MerchantShipmentNo'
        /// </summary>
        [Test]
        public void MerchantShipmentNoTest()
        {
            // TODO unit test for the property 'MerchantShipmentNo'
        }
        /// <summary>
        /// Test the property 'MerchantOrderNo'
        /// </summary>
        [Test]
        public void MerchantOrderNoTest()
        {
            // TODO unit test for the property 'MerchantOrderNo'
        }
        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Test]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
        /// <summary>
        /// Test the property 'TrackTraceNo'
        /// </summary>
        [Test]
        public void TrackTraceNoTest()
        {
            // TODO unit test for the property 'TrackTraceNo'
        }
        /// <summary>
        /// Test the property 'TrackTraceUrl'
        /// </summary>
        [Test]
        public void TrackTraceUrlTest()
        {
            // TODO unit test for the property 'TrackTraceUrl'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

    }

}
