/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing OrderFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderFilterTests
    {
        // TODO uncomment below to declare an instance variable for OrderFilter
        //private OrderFilter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderFilter
            //instance = new OrderFilter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderFilter
        /// </summary>
        [Test]
        public void OrderFilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderFilter
            //Assert.IsInstanceOfType<OrderFilter> (instance, "variable 'instance' is a OrderFilter");
        }

        /// <summary>
        /// Test the property 'Statuses'
        /// </summary>
        [Test]
        public void StatusesTest()
        {
            // TODO unit test for the property 'Statuses'
        }
        /// <summary>
        /// Test the property 'MerchantOrderNos'
        /// </summary>
        [Test]
        public void MerchantOrderNosTest()
        {
            // TODO unit test for the property 'MerchantOrderNos'
        }
        /// <summary>
        /// Test the property 'ExcludeMarketplaceFulfilledOrdersAndLines'
        /// </summary>
        [Test]
        public void ExcludeMarketplaceFulfilledOrdersAndLinesTest()
        {
            // TODO unit test for the property 'ExcludeMarketplaceFulfilledOrdersAndLines'
        }
        /// <summary>
        /// Test the property 'FulfillmentType'
        /// </summary>
        [Test]
        public void FulfillmentTypeTest()
        {
            // TODO unit test for the property 'FulfillmentType'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

    }

}
