/* 
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChannelEngine.Api.Client.Api;
using ChannelEngine.Api.Client.Model;
using ChannelEngine.Api.Client.Client;
using System.Reflection;

namespace ChannelEngine.Api.Client.Test
{
    /// <summary>
    ///  Class for testing ProductMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductMessageTests
    {
        // TODO uncomment below to declare an instance variable for ProductMessage
        //private ProductMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductMessage
            //instance = new ProductMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductMessage
        /// </summary>
        [Test]
        public void ProductMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductMessage
            //Assert.IsInstanceOfType<ProductMessage> (instance, "variable 'instance' is a ProductMessage");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
